### PR TITLE
Fix rest security

### PR DESCRIPTION
**Pull request by spookylukey**
The settings got put in the wrong way around, as demonstrated by the tests which fail without this patch.

I also took the liberty of doing chmod +x on the two scripts so that you can run them like "./runtests.py", in a separate commit.

### CODE REVIEW

**Comment by spookylukey** [comment]
This patch has the disadvantage that the test suite generates a warning. I could add a patch for this if wanted. It's not entirely clear what should be done with the warning instead, but my gut instinct would be to change it to use stdlib `logging` to report the warning instead of printing out to stderr, which is an unhelpful default for a webapp.

**Comment by bartTC** [comment]
Doh, thanks! 

I think the warning is perfectly fine, it warns about this explicit state. I actually wonder why its not vice versa and warns if its enabled. :)

**Comment by spookylukey** [comment]
Thanks, please see also my other PR!

**Comment by bartTC** [comment]
By the way, you can disable the warning with the rest setting:

```
    kwargs = {
        'settings_overrides': {
            'raw_enabled': False,
            'file_insertion_enabled': False,
            'report_level': 3 # error
        }
    }
```

**Pull request merged**
